### ISSUE TITLE
Vaillant API details

### ISSUE THREAD

**Issue by tamlyn** [JohanCosemans/YourHomeServer#1]
Where do I find the `VAILLANT_CLIENT_SECRET` and other details necessary to connect this to my Vaillant Vsmart thermostat?

(Great work on this BTW!)

**Comment by JohanCosemans** [comment]
Hi tamlyn,

If you download and run the precompiled server from http://yourhomeapp.net/download.html you won't need to fill in the client secret. You'll only have to set the Vaillant email address and password in the settings:
![image](https://cloud.githubusercontent.com/assets/3331341/21812179/4db0e06e-d752-11e6-88e9-2341e0dfc3e3.png)

You will need the client secret though to build your own version of the code. It should be in a file called api_keys.properties and placed in the root folder of the project. This file is not made public to avoid that Vaillant changes the key. Send me an email (johan@coteq.be) and I'll send it to you.

Johan

**Comment by tamlyn** [comment]
Thanks.

**Comment by JohanCosemans** [comment]
FYI for all interested in how the vsmart api works:

This is the "secret key": 
VAILLANT_CLIENT_SECRET=929a9f6253babbee1a6e8d4bd51745f0

Summarized, this is the communication that is happening between YourHome and VSmart. It basically is a Netatmo thermostat, but the protocols are not entirely the same:

- Request 1
First you have to make a POST request to
[https://app.netatmo.net/oauth2/token](https://app.netatmo.net//oauth2/token) 
With the body 
`app_version=1.0.0.22&username=my@mail.com&password=mypassword&client_secret=secret&client_id=na_client_android_vaillant&grant_type=password&user_prefix=vaillant` 

This will return you a message similar to this:
- Response 1 
```
{
"access_token": "tokenaedsfsdbdsfdsfsdf",
"refresh_token": "refresh token azesqdsq",
"scope":[
"all_scopes"
],
"expires_in": 10800,
"expire_in": 10800
}
```

- Request 2
Request to 
[https://app.netatmo.net/api/getthermostatsdata](https://app.netatmo.net/api/getthermostatsdata)
with the body
`app_version=1.0.0.22&sync_device_id=all&device_type=NAVaillant&access_token=accesstoken`
- Response 2 
Get these parameters from response 2
```
app_version
sync_device_id
device_type
access_token

```
Now you can start playing around with the thermostat api. This is the request to set the setpoint mode:
More requests are in [https://github.com/JohanCosemans/YourHomeServer/blob/master/src/main/java/net/yourhome/server/thermostat/VaillantVSMartController.java](https://github.com/JohanCosemans/YourHomeServer/blob/master/src/main/java/net/yourhome/server/thermostat/VaillantVSMartController.java)

- Request 3
[https://app.netatmo.net/api/setminormode](https://app.netatmo.net/api/setminormode)
Parameters:
```
app_version (hardcoded)
activate (true/false)
access_token (from response 1)
module_id (from response 2)
device_id (from response 2)setpoint_mode (away/manual)
setpoint_endtimesetpoint_temp  (for manual setpoint mode)
```
- Response 3 is just a confirmation if it succeeded or not.
