### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by dejurin** [JohanCosemans/YourHomeServer#2]
**Report**: https://www.virustotal.com/gui/file/98b4e3d96056d53b5d4efd59541f84d3132df82cb244cf785102c3f628d6fe0c/detection

<img width="1344" alt="Screen Shot 2019-10-07 at 17 13 06" src="https://user-images.githubusercontent.com/4470015/66319448-cf26d080-e925-11e9-9580-10b5f9bd802b.png">
Antiy-AVL

Trojan[Spy]/MSIL.KeyLogger
SecureAge APEX

Malicious
Comodo

Backdoor.Win32.DarkKomet.BC@7etk5a
FireEye

Generic.mg.78e1215f769a3c89
Jiangmin

Backdoor/DarkKomet.ife
Rising

Malware.Agent!1.9F77 (CLASSIC)
SentinelOne (Static ML)

DFI - Suspicious PE
Sophos ML

Heuristic
Trapmine

Malicious.high.ml.score
Acronis

Undetected

**Comment by JohanCosemans** [comment]
Hi Dejurin,

Thanks for letting me know this. I'm sure this are false positives, but will remove the exe file from the package anyhow. It is just a wrapper to start the java process without having to type the commands. (created by bat2exe.com)

Feel free to use YourHome.bat instead or start it by executing java -jar "bin/YourHomeServer-<version>.jar" directly.

Kind regards,
Johan
